/**
 * This will compare the ASTs generated by the C and JS tokenizers, and print out any differences.
 * It is intended to be used with the test samples, but can be used with any wikitext input.
 * 
*/

function cmpObj(obj1, obj2) {
    if( obj1 === obj2 )
        return true;
    else if( obj1 === undefined && obj2 === '')   
        return true;
    else if( obj1 === '' && obj2 === undefined )   
        return true;
    else if( obj1 === false && obj2 === undefined )
        return true;
    else if( obj1 === undefined && obj2 === false )
        return true;
    else if( obj1 === null && obj2 === undefined )
        return true;
    else if( obj1 === undefined && obj2 === null )
        return true;
    else if( typeof obj1 === 0 && typeof obj2 === undefined )
        return true;
    else if( typeof obj1 === undefined && typeof obj2 === 0 )
        return true;
    else
        return false;
}

// Handle differences between the ASTs generated by the C and JS tokenizers.

function getFirstChild(node) {
    if( node.childNodes && node.childNodes.length === 1) {
        return node.childNodes[0];
    }
    return null;
}

/**
 * JS will treat {{NS}} as a template with an empty name, while C will treat it as a magic word with the name "NS".
 * JS: {"type":"root","childNodes":[{"type":"template","childNodes":[{"type":"template-name","childNodes":[{"type":"text","data":"NS"}]}]}]}
 * C:  {"type":"root",
 *          "childNodes":[{"type":"magic-word","name":"ns",
 *              "childNodes":[{"type":"magic-word-name",
 *                  "childNodes":[{"type":"text","data":"NS"}]}]}]}
 * 
 * The C code is correct, so we have to ignore this difference when comparing the ASTs.
 */
function handleTypeMismatch(jsToken, ncToken) {
    // Make sure to validate ALL children!!!
    if( jsToken.type === 'template' && ncToken.type === 'magic-word' ) {
        level1Js = getFirstChild(jsToken);
        level1Nc = getFirstChild(ncToken);

        if( level1Js && level1Js.type === 'template-name' 
            && level1Nc && level1Nc.type === 'magic-word-name' ) {
            level2Js = getFirstChild(level1Js);
            level2Nc = getFirstChild(level1Nc);
            if( level2Js && level2Js.type === 'text' &&  level2Js.data === 'NS'
                && level2Nc === 'NS' ) {
                // This is a known difference between the C and JS tokenizers, so we can ignore it.
                return true;
                
            }
        }

    }
    return false;
}


/**
 * JS will have a single text child node without a data property, while C will have no child nodes and an empty data property.
 * expected.Json: {"type":"ext-inner","name":"section","childNodes":[{"type":"text"}]}
 * actual.Json: {"type":"ext-inner","name":"section","childNodes":[]}
 * --OR--
 * actual.Json: {"type":"ext-inner","name":"section"}
*/
function handleChildrenMismatch(jsToken, ncToken) {
    // ONLY handle if one is empty and the other has just a single child!!!
    if((! jsToken.childNodes || jsToken.childNodes.length === 0) && ncToken.childNodes && ncToken.childNodes.length === 1 
        || (! ncToken.childNodes || ncToken.childNodes.length === 0) && jsToken.childNodes && jsToken.childNodes.length === 1 ) {
        if( jsToken.type === 'ext-inner' && ncToken.type === 'ext-inner' ) {
            if( jsToken.name === 'section' ) {
                if( jsToken.childNodes.length === 1 && jsToken.childNodes[0].type === 'text' && (! ncToken.childNodes || ncToken.childNodes.length === 0) ) {
                    // This is a known difference between the C and JS tokenizers, so we can ignore it.
                    return true;
                }
            }
        }
    }
    return false;
}

function compareAST(jsToken, ncToken, parents= []) {
    if( jsToken.type !== 'text' && jsToken.type !== ncToken.type ) {
        // This handles the comparison for ALL children, so we don't have to worry about any differences in the children when comparing the data properties of the tokens.
        if( handleTypeMismatch(jsToken, ncToken) ) {
            return { success: true };
        }else {
            return { success: false,  kind: 'type', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Type mismatch: JS ${jsToken.type} vs C ${ncToken.type}` };    
        }
    }
    if( jsToken.type === 'heading' ) {
        // if( !cmpObj(jsToken.level, ncToken.level) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Heading level mismatch: JS ${jsToken.level} vs C ${ncToken.level}` };
        // }
        // if( !cmpObj(jsToken.id, ncToken.id) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Heading id mismatch: JS "${jsToken.id}" vs C "${ncToken.id}"` };
        // }
    } else if( jsToken.type === 'text' ) {
        if( ncToken == null ) {
            ncToken = { type: 'text', data: '' };
        }else if( typeof ncToken === 'string' ) {
            ncToken = { type: 'text', data: ncToken };
        }
        if( !cmpObj(jsToken.data, ncToken.data) ) {
            return { success: false,  kind: 'text', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Text mismatch: JS "${jsToken.data}" vs C "${ncToken.data}"` };
        }
    } else if (jsToken.type === 'redirect') {
        if( !cmpObj(jsToken.pre, ncToken.pre) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Redirect pre mismatch: JS "${jsToken.pre}" vs C "${ncToken.pre}"` };
        }
        if( !cmpObj(jsToken.post, ncToken.post) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Redirect post mismatch: JS "${jsToken.post}" vs C "${ncToken.post}"` };
        }
        if( !cmpObj(jsToken.link, ncToken.link) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Redirect link mismatch: JS "${jsToken.link}" vs C "${ncToken.link}"` };
        }
        if( !cmpObj(jsToken.display, ncToken.display) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Redirect display mismatch: JS "${jsToken.display}" vs C "${ncToken.display}"` };
        }
    } else if (jsToken.type === 'ext') {
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext name mismatch: JS ${jsToken.name} vs C ${ncToken.name}` };
        }
        if( !cmpObj(jsToken.attr, ncToken.attr) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext attr mismatch: JS "${jsToken.attr}" vs C "${ncToken.attr}"` };
        }
        if( !cmpObj(jsToken.inner, ncToken.inner) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext inner mismatch: JS "${jsToken.inner}" vs C "${ncToken.inner}"` };
        }
        if( !cmpObj(jsToken.closing, ncToken.closing) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext closing mismatch: JS "${jsToken.closing}" vs C "${ncToken.closing}"` };
        }
        if( !cmpObj(jsToken.self_closing, ncToken.self_closing) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext self_closing mismatch: JS ${jsToken.self_closing} vs C ${ncToken.self_closing}` };
        }
    } else if (jsToken.type === 'include') {
        if( !cmpObj(jsToken.tag, ncToken.tag) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Include tag mismatch: JS "${jsToken.tag}" vs C "${ncToken.tag}"` };
        }
        if( !cmpObj(jsToken.attr, ncToken.attr) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Include attr mismatch: JS "${jsToken.attr}" vs C "${ncToken.attr}"` };
        }
        if( !cmpObj(jsToken.inner, ncToken.inner) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Include inner mismatch: JS "${jsToken.inner}" vs C "${ncToken.inner}"` };
        }
        if( !cmpObj(jsToken.closing, ncToken.closing) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Include closing mismatch: JS "${jsToken.closing}" vs C "${ncToken.closing}"` };
        }
    } else if (jsToken.type === 'html') {
        if( !cmpObj(jsToken.self_closing, ncToken.self_closing) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Html self_closing mismatch: JS ${jsToken.self_closing} vs C ${ncToken.self_closing}` };
        }
        // if( !cmpObj(jsToken.closing, ncToken.closing) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Html closing mismatch: JS ${jsToken.closing} vs C ${ncToken.closing}` };
        // }
        if( !cmpObj(jsToken.orig_tag, ncToken.orig_tag) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Html orig_tag mismatch: JS "${jsToken.orig_tag}" vs C "${ncToken.orig_tag}"` };
        }
    } else if (jsToken.type === 'td') {
        if( !cmpObj(jsToken.inner_syntax, ncToken.inner_syntax) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Td inner_syntax mismatch: JS "${jsToken.inner_syntax}" vs C "${ncToken.inner_syntax}"` };
        }
    } else if (jsToken.type === 'dunder') {
        if( !cmpObj(jsToken.case_sensitive, ncToken.case_sensitive) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Dunder case_sensitive mismatch: JS ${jsToken.case_sensitive} vs C ${ncToken.case_sensitive}` };
        }
        if( !cmpObj(jsToken.fullwidth, ncToken.fullwidth) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Dunder fullwidth mismatch: JS ${jsToken.fullwidth} vs C ${ncToken.fullwidth}` };
        }
    } else if (jsToken.type === 'quote') {
        // if( !cmpObj(jsToken.bold, ncToken.bold) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Quote bold mismatch: JS ${jsToken.bold} vs C ${ncToken.bold}` };
        // }
        // if( !cmpObj(jsToken.italic, ncToken.italic) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Quote italic mismatch: JS ${jsToken.italic} vs C ${ncToken.italic}` };
        // }
    } else if (jsToken.type === 'image-parameter') {
        // if( !cmpObj(jsToken.value, ncToken.value) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Image-parameter value mismatch: JS "${jsToken.value}" vs C "${ncToken.value}"` };
        // }
        // if( !cmpObj(jsToken.width, ncToken.width) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Image-parameter width mismatch: JS "${jsToken.width}" vs C "${ncToken.width}"` };
        // }
        // if( !cmpObj(jsToken.height, ncToken.height) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Image-parameter height mismatch: JS "${jsToken.height}" vs C "${ncToken.height}"` };
        // }
    } else if (jsToken.type === 'ext-link') {
        // if( !cmpObj(jsToken.link, ncToken.link) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext-link link mismatch: JS "${jsToken.link}" vs C "${ncToken.link}"` };
        // }
        // if( !cmpObj(jsToken.protocol, ncToken.protocol) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext-link protocol mismatch: JS "${jsToken.protocol}" vs C "${ncToken.protocol}"` };
        // }
        // if( !cmpObj(jsToken.innerText, ncToken.innerText) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Ext-link innerText mismatch: JS "${jsToken.innerText}" vs C "${ncToken.innerText}"` };
        // }
    } else if (jsToken.type === 'imagemap-link') {
        // if( !cmpObj(jsToken.link, ncToken.link) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Imagemap-link link mismatch: JS "${jsToken.link}" vs C "${ncToken.link}"` };
        // }
    } else if (jsToken.type === 'template' || jsToken.type === 'magic-word') {
        // if( !cmpObj(jsToken.modifier, ncToken.modifier) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template modifier mismatch: JS "${jsToken.modifier}" vs C "${ncToken.modifier}"` };
        // }
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template name mismatch: JS "${jsToken.name}" vs C "${ncToken.name}"` };
        }
        // if( !cmpObj(jsToken.module, ncToken.module) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template module mismatch: JS "${jsToken.module}" vs C "${ncToken.module}"` };
        // }
        // if( !cmpObj(jsToken.function, ncToken.function) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template function mismatch: JS "${jsToken.function}" vs C "${ncToken.function}"` };
        // }
        // if( !cmpObj(jsToken.duplication, ncToken.duplication) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template duplication mismatch: JS ${jsToken.duplication} vs C ${ncToken.duplication}` };
        // }
        // if( !cmpObj(jsToken.anonCount, ncToken.anonCount) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Template anonCount mismatch: JS ${jsToken.anonCount} vs C ${ncToken.anonCount}` };
        // }
    } else if (jsToken.type === 'parameter') {
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Parameter name mismatch: JS "${jsToken.name}" vs C "${ncToken.name}"` };
        }
        // if( !cmpObj(jsToken.value, ncToken.value) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Parameter value mismatch: JS "${jsToken.value}" vs C "${ncToken.value}"` };
        // }
        // if( !cmpObj(jsToken.anon, ncToken.anon) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Parameter anon mismatch: JS ${jsToken.anon} vs C ${ncToken.anon}` };
        // }
        // if( !cmpObj(jsToken.duplicated, ncToken.duplicated) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Parameter duplicated mismatch: JS ${jsToken.duplicated} vs C ${ncToken.duplicated}` };
        // }
    } else if (jsToken.type === 'arg') {
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Arg name mismatch: JS "${jsToken.name}" vs C "${ncToken.name}"` };
        }
        // if( !cmpObj(jsToken.default, ncToken.default) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Arg default mismatch: JS "${jsToken.default}" vs C "${ncToken.default}"` };
        // }
    } else if (jsToken.type === 'converter') {
        if( !cmpObj(jsToken.variant, ncToken.variant) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Converter variant mismatch: JS "${jsToken.variant}" vs C "${ncToken.variant}"` };
        }
        if( !cmpObj(jsToken.unidirectional, ncToken.unidirectional) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Converter unidirectional mismatch: JS ${jsToken.unidirectional} vs C ${ncToken.unidirectional}` };
        }
        if( !cmpObj(jsToken.bidirectional, ncToken.bidirectional) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Converter bidirectional mismatch: JS ${jsToken.bidirectional} vs C ${ncToken.bidirectional}` };
        }
    } else if (jsToken.type === 'converter-flags') {
        if( !cmpObj(jsToken.flags, ncToken.flags) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Converter-flags flags mismatch: JS ${jsToken.flags} vs C ${ncToken.flags}` };
        }
    } else if (jsToken.type === 'attributes') {
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Attributes name mismatch: JS "${jsToken.name}" vs C "${ncToken.name}"` };
        }
        if( !cmpObj(jsToken.className, ncToken.className) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Attributes className mismatch: JS "${jsToken.className}" vs C "${ncToken.className}"` };
        }
        if( !cmpObj(jsToken.id, ncToken.id) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Attributes id mismatch: JS "${jsToken.id}" vs C "${ncToken.id}"` };
        }
        if( !cmpObj(jsToken.sanitized, ncToken.sanitized) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Attributes sanitized mismatch: JS ${jsToken.sanitized} vs C ${ncToken.sanitized}` };
        }
    } else if (jsToken.type === 'atom') {
        if( !cmpObj(jsToken.type, ncToken.type) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Atom type mismatch: JS ${jsToken.type} vs C ${ncToken.type}` };
        }
    } else if (jsToken.type === 'syntax') {
        if( !cmpObj(jsToken.type, ncToken.type) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Syntax type mismatch: JS ${jsToken.type} vs C ${ncToken.type}` };
        }
    } else if (jsToken.type === 'comment') {
        // if( !cmpObj(jsToken.closed, ncToken.closed) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Comment closed mismatch: JS ${jsToken.closed} vs C ${ncToken.closed}` };
        // }
    } else if (jsToken.type === 'onlyinclude') {
        if( !cmpObj(jsToken.innerText, ncToken.innerText) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Onlyinclude innerText mismatch: JS "${jsToken.innerText}" vs C "${ncToken.innerText}"` };
        }
    } else if (jsToken.type === 'param-line') {
        if( !cmpObj(jsToken.name, ncToken.name) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Param-line name mismatch: JS "${jsToken.name}" vs C "${ncToken.name}"` };
        }
    } else if (jsToken.type === 'list-range') {
        if( !cmpObj(jsToken.previousSibling, ncToken.previousSibling) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List-range previousSibling mismatch: JS ${jsToken.previousSibling} vs C ${ncToken.previousSibling}` };
        }
        if( !cmpObj(jsToken.nextSibling, ncToken.nextSibling) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List-range nextSibling mismatch: JS ${jsToken.nextSibling} vs C ${ncToken.nextSibling}` };
        }
        if( !cmpObj(jsToken.previousElementSibling, ncToken.previousElementSibling) ) {
            return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List-range previousElementSibling mismatch: JS ${jsToken.previousElementSibling} vs C ${ncToken.previousElementSibling}` };
        }
    } else if (jsToken.type === 'list' || jsToken.type === 'dd') {
        // if( !cmpObj(jsToken.indent, ncToken.indent) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List indent mismatch: JS ${jsToken.indent} vs C ${ncToken.indent}` };
        // }
        // if( !cmpObj(jsToken.dd, ncToken.dd) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List dd mismatch: JS ${jsToken.dd} vs C ${ncToken.dd}` };
        // }
        // if( !cmpObj(jsToken.dt, ncToken.dt) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List dt mismatch: JS ${jsToken.dt} vs C ${ncToken.dt}` };
        // }
        // if( !cmpObj(jsToken.ul, ncToken.ul) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List ul mismatch: JS ${jsToken.ul} vs C ${ncToken.ul}` };
        // }
        // if( !cmpObj(jsToken.ol, ncToken.ol) ) {
        //     return { success: false,  kind: 'data', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `List ol mismatch: JS ${jsToken.ol} vs C ${ncToken.ol}` };
        // }
    }
    if( jsToken.type !== 'text' && !cmpObj(jsToken.childNodes && jsToken.childNodes.length || 0, ncToken.childNodes && ncToken.childNodes.length || 0 ) ) {
        if( handleChildrenMismatch(jsToken, ncToken) ) {
            return { success: true };
        }
        return { success: false,  kind: 'children', jsToken: jsToken, ncToken: ncToken, parents: parents, reason: `Children count mismatch: JS ${jsToken.childNodes ? jsToken.childNodes.length : 0} vs C ${ncToken.childNodes ? ncToken.childNodes.length : 0}` };

    }
    if( jsToken.childNodes ) {
        for( let i = 0; i < jsToken.childNodes.length; i++ ) {
            parents.push({ js: jsToken, c: ncToken });
            const result = compareAST(jsToken.childNodes[i], ncToken.childNodes[i], parents);
            if( !result.success ) {
                return result;
            }
            parents.pop();
        }
    }
    
    return { success: true };
}




exports.compareAST = compareAST;