/*
 * Test all items.  Start with the test_cast.js, test_parsoid.js, test_wikitext.js, and test_export.js files.  Stop on first failure.
 * The test_wikitext.js file will load wikitext samples from the wikitext directory, which are generated by test_export.js.
 * If a sample fails, it will be saved to the wikitext directory for further analysis.
 */
const { runTests } = require('./helpers');
const castTests = require("./test_cast").castTests;
const parsoidTests = require("./test_parsoid").parsoidTests;
const testWikitext = require("./test_wikitext").testWikitext;
const testExport = require("./test_export").testExport;

async function testAll() {
  console.log("Running cast tests...");
  for (const test of castTests) {
    const ok = runTests([test], { name: "wiki-cast" });
    if (!ok) {
      console.error(`FAILED: stopping on first failure in cast tests`);
      process.exit(2);
    }
  }
  console.log("Regression Cast tests passed");

  console.log("Running parsoid tests...");
  for (const test of parsoidTests) {
    const ok = runTests([test], { name: "parsoid" });
    if (!ok) {
      console.error(`FAILED: stopping on first failure in parsoid tests`);
      process.exit(2);
    }
  }
  console.log("Regression Parsoid tests passed");

  console.log("Running wikitext tests...");
  testWikitext();
  console.log("Regression Wikitext tests passed");

  console.log("Running export tests...");
  await testExport(process.argv);

  console.log("Getting latest failing wikitext samples");
  testWikitext();

  console.log("All tests passed");
  process.exit(0);
}

if (process.argv[1] === __filename) {
  testAll();
}
