#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const assert = require('assert');

let Ajv;
try {
  Ajv = require('ajv');
} catch (e) {
  console.error('ERROR: ajv is required for schema validation.');
  console.error('Install it (for example): npm i ajv');
  process.exit(1);
}

function loadNativeParser() {
  const releasePath = path.join(__dirname, '..', 'build', 'Release', 'wiki-cast.node');
  const debugPath = path.join(__dirname, '..', 'build', 'Debug', 'wiki-cast.node');
  try {
    return require(releasePath);
  } catch (e) {
    return require(debugPath);
  }
}

function loadWikitextSamples(dir) {
  const files = fs.readdirSync(dir).filter((f) => !f.startsWith('.')).sort();
  const samples = [];
  for (const file of files) {
    const filePath = path.join(dir, file);
    const st = fs.statSync(filePath);
    if (st.isFile()) {
      samples.push({
        file,
        content: fs.readFileSync(filePath, 'utf8'),
      });
    }
  }
  return samples;
}

function decodeJsonPointerSegment(seg) {
  return seg.replace(/~1/g, '/').replace(/~0/g, '~');
}

function getByJsonPointer(root, pointer) {
  if (!pointer || pointer === '/') {
    return root;
  }
  const parts = pointer.split('/').slice(1).map(decodeJsonPointerSegment);
  let cur = root;
  for (const p of parts) {
    if (cur === null || typeof cur !== 'object') {
      return undefined;
    }
    cur = cur[p];
  }
  return cur;
}

function trimJson(value, maxLen = 700) {
  let text;
  try {
    text = JSON.stringify(value);
  } catch (e) {
    return String(value);
  }
  if (text.length <= maxLen) {
    return text;
  }
  return `${text.slice(0, maxLen)} ...<trimmed ${text.length - maxLen} chars>`;
}

function testSchema() {
  const repoRoot = path.resolve(__dirname, '..', '..', '..');
  const schemaPath = path.join(repoRoot, 'config', 'wiki-cast.json');
  const configPath = path.join(repoRoot, 'config', 'enwiki.json');
  const sampleDir = path.join(__dirname, 'wikitext');

  if (!fs.existsSync(schemaPath)) {
    throw new Error(`Schema not found: ${schemaPath}`);
  }
  if (!fs.existsSync(configPath)) {
    throw new Error(`Config not found: ${configPath}`);
  }
  if (!fs.existsSync(sampleDir)) {
    throw new Error(`Sample dir not found: ${sampleDir}`);
  }

  const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf8'));
  const ajv = new Ajv({
    strict: false,
    allErrors: true,
  });
  const validate = ajv.compile(schema);

  const nativeParser = loadNativeParser();
  nativeParser.config = String(configPath);

  const samples = loadWikitextSamples(sampleDir);
  if (samples.length === 0) {
    throw new Error(`No samples found in ${sampleDir}`);
  }

  let passCount = 0;
  for (const sample of samples) {
    const root = nativeParser.parse(Buffer.from(sample.content, 'utf8'), false, 10);
    assert(root && typeof root.toInternalJson === 'function', 'Native root token missing toInternalJson()');

    let internalJsonText;
    try {
      internalJsonText = root.toInternalJson();
    } finally {
      if (root && typeof root._freeNative === 'function') {
        try {
          root._freeNative();
        } catch (e) {
          // best-effort cleanup
        }
      }
    }

    let ast;
    try {
      ast = JSON.parse(internalJsonText);
    } catch (e) {
      console.error(`FAIL ${sample.file}`);
      console.error('Invalid JSON generated by toInternalJson():');
      console.error(e && e.message ? e.message : e);
      return 1;
    }

    const ok = validate(ast);
    if (!ok) {
      console.error(`FAIL ${sample.file}`);
      console.error(`Sample path: ${path.join(sampleDir, sample.file)}`);
      console.error('Schema validation failed for internal JSON.');
      const errs = validate.errors || [];
      for (let i = 0; i < Math.min(errs.length, 10); i++) {
        const err = errs[i];
        const pointer = err.instancePath || '/';
        const node = getByJsonPointer(ast, pointer);
        const parentPointer = pointer === '/' ? '/' : pointer.replace(/\/[^/]*$/, '') || '/';
        const parent = getByJsonPointer(ast, parentPointer);
        console.error(
          `  - file=${sample.file} path=${pointer} schemaPath=${err.schemaPath || ''} keyword=${err.keyword} message=${err.message}`
        );
        console.error(`    value=${trimJson(node)}`);
        console.error(`    parentPath=${parentPointer} parent=${trimJson(parent)}`);
      }
      return 1;
    }

    passCount++;
  }

  console.log(`Schema test completed: ${passCount} passed, 0 failed`);
  return 0;
}

if (require.main === module) {
  const code = testSchema();
  process.exit(code);
}

module.exports = { testSchema };
