/*
 * Test all items.  Start with the test_cast.js, test_parsoid.js, test_wikitext.js, and test_export.js files.  Stop on first failure.
 * The test_wikitext.js file will load wikitext samples from the wikitext directory, which are generated by test_export.js.
 * If a sample fails, it will be saved to the wikitext directory for further analysis.
 */
const { runTests } = require('./helpers');
const castTests = require("./test_cast").castTests;
const tempTests = require("./test_temp").tempTests;
const parsoidTests = require("./test_parsoid").parsoidTests;
const testWikitext = require("./test_wikitext").testWikitext;
const testExport = require("./test_export").testExport;

async function testAll() {
  console.log("Running current failure...");
  for (const test of tempTests) {
    const ok = runTests([test], { name: "wiki-cast" });
    if (!ok) {
      console.error(`FAILED: The current failure is still failing.`);
      process.exit(1);
    }
  }
  console.log("Awesome, the current failure is no longer failing!  Lets check the regression tests...");

  for (const test of castTests) {
    const ok = runTests([test], { name: "wiki-cast" });
    if (!ok) {
      console.error(`FAILED: stopping on first failure in cast tests`);
      process.exit(2);
    }
  }
  console.log("Regression CAST tests passed");

  for (const test of parsoidTests) {
    const ok = runTests([test], { name: "parsoid" });
    if (!ok) {
      console.error(`FAILED: stopping on first failure in parsoid tests`);
      process.exit(3);
    }
  }
  console.log("Regression Parsoid tests passed");

  let ok = testWikitext();
  if (!ok) {
    console.error(`FAILED: stopping on first failure in wikitext tests`);
    process.exit(4);
  }
  console.log("Regression Wikitext tests passed");

  console.log("Running export tests...");
  ok = await testExport(process.argv);
  if (!ok) {
    console.error(`FAILED: Getting failure point in export tests`);
    // VBerify that the copied wikitext fails and have it output the smallest diff for analysis
    ok = testWikitext();
    if (!ok) {
      console.error(`FAILED: wikitests also failed.`);
      process.exit(6);
    }else {
      console.error(`FAILED: wikitests passed, but export tests failed.  This is unexpected and should be investigated.`);
      process.exit(5);
    }
  }

  console.log("All regression tests passed");
  process.exit(0);
}

if (process.argv[1] === __filename) {
  (async () => {
    await testAll();
  })();
}
